server:
    port: 8080

spring:
    datasource:
        url: jdbc:h2:mem:rangemanager
        driverClassName: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true
        hibernate:
            ddl-auto: none
        database-platform: org.hibernate.dialect.H2Dialect
    flyway:
        enabled: true
        locations:
          - db.migration
        encoding: UTF-8
springdoc:
    use-management-port: true

management:
    endpoints:
        web:
            exposure:
                include: health, openapi, swagger-ui
    server:
        port: 9090

logging:
    level:
        org.springframework.web: "info"